### ISSUE TITLE
doesn't work on chrome windows

### ISSUE THREAD

**Issue by qiangqiang101** [nguyenthuongvo/Vox#3]
works on bluefy ios
tried on chrome Version 94.0.4606.81, chrome flags enabled
after pairing with sp110e, settings not getting and buttons don't work
![Capture](https://user-images.githubusercontent.com/11488961/137166481-195a031b-d5c4-41ca-ae3f-210129663757.JPG)

**Comment by nguyenthuongvo** [comment]
Which OS you are using? Windows or LInux

**Comment by qiangqiang101** [comment]
Windows 10

**Comment by nguyenthuongvo** [comment]
It's not work on Windows 10. The issue from OS. I have try on Chrome - Linux, it's works well.

**Comment by qiangqiang101** [comment]
Ok thanks
